import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Route, Routes, useLocation } from 'react-router-dom';
import './styles.css';
import './shop.css';

// Locally hosted campaign images keep the gallery dependable without third-party requests.
const gallery = ['/images/hero.png', '/images/story.png', '/images/flatlay.png', '/images/lifestyle.png', '/images/heirloom.png'];
const faqs = ['What does Nirvalya sell?', 'Do you make custom bangle sets?', 'Can I order custom festival or celebration bangle sets?', 'How do I place a custom order?', 'Do you deliver across India?', 'What sizes are available?', 'Is gift packaging available?'];

function Header(){ const [open,setOpen]=useState(false); const loc=useLocation(); return <><div className="heritage-strip"><span>Crafted with care since 1994</span><i>✦</i><span>Traditional craft, thoughtfully brought online</span></div><header><Link className="brand" to="/">NIRVALYA<span>Since 1994</span></Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?'×':'☰'}</button><nav className={open?'open':''}><Link className={loc.pathname==='/'?'active':''} to="/" onClick={()=>setOpen(false)}>Home</Link><Link className={loc.pathname==='/shop'?'active':''} to="/shop" onClick={()=>setOpen(false)}>Shop</Link></nav></header></> }
function Newsletter(){const [submitted,setSubmitted]=useState(false); return <section className="subscribe"><div><p className="eyebrow">A SMALL NOTE FROM US</p><h2>Subscribe</h2></div><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}>{submitted?<p className="success">Thank you. You’re on the list.</p>:<><label><span>Email address</span><input required type="email" placeholder="you@example.com"/></label><button>Sign up <span>→</span></button></>}<small>Sign up for our monthly newsletter of secrets for success.</small></form></section>}
function Story(){return <section id="story" className="story"><div className="section-intro"><p className="eyebrow">THE HEART OF NIRVALYA</p><h2>Our Nirvalya<br/>Story</h2><p>Three decades of knowing that the right bangle is never just a bangle.</p></div><article className="story-row"><div className="story-image story-one"><img src="/images/story.png" alt="Gold jewellery detail"/></div><div className="copy"><p className="eyebrow">01 / SINCE 1994</p><h3>Our Story</h3><p>It started with a small bangle shop in 1994. No grand investment, no elaborate plan—just a family that understood the quiet joy of finding the piece that feels exactly right.</p><p>For 30 years, we learned what lasts, what delights, and what brings women back with their daughters. Nirvalya is that knowledge, now brought online.</p><blockquote>Same craft.<br/>Same care.<br/><em>New chapter.</em></blockquote></div></article><article className="story-row reverse"><div className="story-image story-two"><img src="/images/flatlay.png" alt="Traditional bangle stack"/></div><div className="copy"><p className="eyebrow">02 / OUR PROMISE</p><h3>Our Mission</h3><p>Not too tight. Not too loose. Just right. We exist for that little moment when you look at your wrist and know: <em>this one is mine.</em></p><p>From weddings and festivals to an ordinary Tuesday, we bring real craft, real quality, and real care to Indian women everywhere—at a price that feels fair.</p><blockquote>Not jewellery that impresses people.<br/><em>Jewellery that feels like you.</em></blockquote></div></article><article className="story-row"><div className="story-image story-three"><img src="/images/lifestyle.png" alt="Fine gold bangle"/></div><div className="copy"><p className="eyebrow">03 / LOOKING AHEAD</p><h3>Our Vision</h3><p>We grew up watching our mother select bangles with care—no shortcuts, no compromises. We envision a world where every Indian woman can find jewellery that is beautiful, honest, and worth keeping.</p><p>Not fast fashion. Not something that fades. Not something priced behind glass. Quality, real price, real feeling.</p><blockquote>One wrist, at a time.<br/><em>Wear what feels like you.</em></blockquote></div></article></section>}
function Gallery(){return <section className="gallery"><div className="gallery-title"><p className="eyebrow">A LITTLE GLIMMER</p><h2>Gallery</h2><p>Made for the moments you keep.</p></div><div className="gallery-grid">{gallery.map((image,i)=><img key={image} src={image} alt={`Nirvalya jewellery ${i+1}`}/>)}</div></section>}
function FAQ(){const [active,setActive]=useState(null);return <section className="faq"><p className="eyebrow">WE’RE HERE TO HELP</p><h2>Frequently Asked<br/>Questions</h2><p className="faq-intro">Please reach us at <a href="mailto:souravchauhan039@gmail.com">souravchauhan039@gmail.com</a> if you cannot find an answer to your question.</p><div className="faq-list">{faqs.map((q,i)=><div className="faq-item" key={q}><button onClick={()=>setActive(active===i?null:i)}><span>{q}</span><b>{active===i?'−':'+'}</b></button>{active===i&&<div className="faq-answer">We’re preparing the details for this question. Please contact us and we’ll be delighted to help.</div>}</div>)}</div></section>}
function Footer(){return <footer><div className="footer-brand">NIRVALYA<span>Since 1994</span></div><div><p className="eyebrow">CONNECT WITH US</p><div className="socials"><a className="social-icon" href="https://www.facebook.com/share/19eknLqD2m/" target="_blank" rel="noreferrer" aria-label="Nirvalya on Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.2 0-5 2-5 5v3H6v4h3v7h4v-7h3l1-4h-4V9c0-.7.3-1 1-1Z"/></svg></a><a className="social-icon" href="https://www.instagram.com/shop.nirvalya" target="_blank" rel="noreferrer" aria-label="Nirvalya on Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" className="fill"/></svg></a></div></div><div className="legal"><span>© 2026 Nirvalya. All rights reserved.</span><Link to="/privacy-policy">Privacy Policy</Link><Link to="/terms-and-conditions">Terms & Conditions</Link></div></footer>}
function Home(){return <><Header/><main><section className="hero"><img src="/images/hero.png" alt="Nirvalya gold bangle collection"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">A NEW CHAPTER IN TRADITION</p><h1>Something<br/><i>beautiful</i> is coming.</h1><p className="hero-text">Bangles rooted in 30 years of family craft. Launching soon on Nirvalya. Sign up to be first—we will make it worth your while.</p><a className="arrow-link" href="#story">Discover our story <span>→</span></a></div><div className="hero-side">EST. 1994 &nbsp; · &nbsp; INDIA</div></section><Newsletter/><Story/><Gallery/><FAQ/></main><Footer/></>}
function SimplePage({title,children}){return <><Header/><main className="simple-page"><p className="eyebrow">NIRVALYA / SINCE 1994</p><h1>{title}</h1>{children}</main><Footer/></>}
function Shop(){return <><Header/><main className="shop-page"><div className="shop-copy"><p className="eyebrow">NIRVALYA / FIRST COLLECTION</p><h1>Something to<br/><i>hold close.</i></h1><p>We’re thoughtfully preparing our first collection of bangles for the moments you keep.</p><Link className="filled-link" to="/">Return home <span>→</span></Link></div><div className="bangle-stage" aria-label="Animated gold bangle illustration"><span className="bangle bangle-one"/><span className="bangle bangle-two"/><span className="bangle bangle-three"/><span className="bangle bangle-four"/><span className="stage-note">COMING SOON<br/><i>Since 1994</i></span></div></main><Footer/></>}
function Legal({terms}){let title=terms?'Terms & Conditions':'Privacy Policy'; return <SimplePage title={title}><div className="legal-copy"><p>Last updated: September 2026</p><h3>{terms?'Welcome to Nirvalya':'Your privacy matters'}</h3><p>{terms?'These terms govern your use of the Nirvalya website. By using the site, you agree to use it respectfully and in accordance with applicable law.':'Nirvalya respects your privacy. We only use information you voluntarily provide, such as an email submitted to our newsletter, to communicate with you about the brand and our launch.'}</p><p>For any questions, please contact <a href="mailto:souravchauhan039@gmail.com">souravchauhan039@gmail.com</a>.</p></div></SimplePage>}
function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/shop" element={<Shop/>}/><Route path="/privacy-policy" element={<Legal/>}/><Route path="/terms-and-conditions" element={<Legal terms/>}/></Routes>}; createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
